config/routes.rb
FestivalManager::Application.routes.draw do

  resources :event_types

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',	:to => "users#new"
  match '/signin',	:to => 'sessions#new'
  match '/signout',	:to => 'sessions#destroy'
  
  match '/contact', :to => "pages#contact"
  match '/about', :to => "pages#about"
  match '/about/lisa-vickerage', :to => "pages#lisavickerage"
  match '/about/ellen-wray', :to => "pages#ellenwray"

  resources :venues
  resources :events

   root :to => "pages#home"

end

app/models/venue.rb
# == Schema Information
# Schema version: 20101125182808
#
# Table name: venues
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  address1   :string(255)
#  address2   :string(255)
#  city       :string(255)
#  county     :string(255)
#  postcode   :string(255)
#  telno      :string(255)
#  faxno      :string(255)
#  email      :string(255)
#  website    :string(255)
#  contact    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Venue < ActiveRecord::Base
	has_many :events
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  # GET /venues
  # GET /venues.xml
  def index
    @venues = Venue.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @venues }
    end
  end

  # GET /venues/1
  # GET /venues/1.xml
  def show
    @venue = Venue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @venue }
    end
  end

  # GET /venues/new
  # GET /venues/new.xml
  def new
    @venue = Venue.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @venue }
    end
  end

  # GET /venues/1/edit
  def edit
    @venue = Venue.find(params[:id])
  end

  # POST /venues
  # POST /venues.xml
  def create
    @venue = Venue.new(params[:venue])

    respond_to do |format|
      if @venue.save
        format.html { redirect_to(@venue, :notice => 'Venue was successfully created.') }
        format.xml  { render :xml => @venue, :status => :created, :location => @venue }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @venue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /venues/1
  # PUT /venues/1.xml
  def update
    @venue = Venue.find(params[:id])

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to(@venue, :notice => 'Venue was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @venue.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.xml
  def destroy
    @venue = Venue.find(params[:id])
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to(venues_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :county %><br />
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br />
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :telno %><br />
    <%= f.text_field :telno %>
  </div>
  <div class="field">
    <%= f.label :faxno %><br />
    <%= f.text_field :faxno %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<h1>Listing venues</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address1</th>
    <th>Address2</th>
    <th>City</th>
    <th>County</th>
    <th>Postcode</th>
    <th>Telno</th>
    <th>Faxno</th>
    <th>Email</th>
    <th>Website</th>
    <th>Contact</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @venues.each do |venue| %>
  <tr>
    <td><%= venue.name %></td>
    <td><%= venue.address1 %></td>
    <td><%= venue.address2 %></td>
    <td><%= venue.city %></td>
    <td><%= venue.county %></td>
    <td><%= venue.postcode %></td>
    <td><%= venue.telno %></td>
    <td><%= venue.faxno %></td>
    <td><%= venue.email %></td>
    <td><%= venue.website %></td>
    <td><%= venue.contact %></td>
    <td><%= link_to 'Show', venue %></td>
    <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
    <td><%= link_to 'Destroy', venue, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @venue.name %>
</p>

<p>
  <b>Address1:</b>
  <%= @venue.address1 %>
</p>

<p>
  <b>Address2:</b>
  <%= @venue.address2 %>
</p>

<p>
  <b>City:</b>
  <%= @venue.city %>
</p>

<p>
  <b>County:</b>
  <%= @venue.county %>
</p>

<p>
  <b>Postcode:</b>
  <%= @venue.postcode %>
</p>

<p>
  <b>Telno:</b>
  <%= @venue.telno %>
</p>

<p>
  <b>Faxno:</b>
  <%= @venue.faxno %>
</p>

<p>
  <b>Email:</b>
  <%= @venue.email %>
</p>

<p>
  <b>Website:</b>
  <%= @venue.website %>
</p>

<p>
  <b>Contact:</b>
  <%= @venue.contact %>
</p>


<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>