config/routes.rb
FestivalManager::Application.routes.draw do

  resources :event_types

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup',	:to => "users#new"
  match '/signin',	:to => 'sessions#new'
  match '/signout',	:to => 'sessions#destroy'
  
  match '/contact', :to => "pages#contact"
  match '/about', :to => "pages#about"
  match '/about/lisa-vickerage', :to => "pages#lisavickerage"
  match '/about/ellen-wray', :to => "pages#ellenwray"

  resources :venues
  resources :events

   root :to => "pages#home"

end

app/controllers/event_types_controller.rb
class EventTypesController < ApplicationController
  # GET /event_types
  # GET /event_types.xml
  def index
    @event_types = EventType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @event_types }
    end
  end

  # GET /event_types/1
  # GET /event_types/1.xml
  def show
    @event_type = EventType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event_type }
    end
  end

  # GET /event_types/new
  # GET /event_types/new.xml
  def new
    @event_type = EventType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event_type }
    end
  end

  # GET /event_types/1/edit
  def edit
    @event_type = EventType.find(params[:id])
  end

  # POST /event_types
  # POST /event_types.xml
  def create
    @event_type = EventType.new(params[:event_type])

    respond_to do |format|
      if @event_type.save
        format.html { redirect_to(@event_type, :notice => 'Event type was successfully created.') }
        format.xml  { render :xml => @event_type, :status => :created, :location => @event_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /event_types/1
  # PUT /event_types/1.xml
  def update
    @event_type = EventType.find(params[:id])

    respond_to do |format|
      if @event_type.update_attributes(params[:event_type])
        format.html { redirect_to(@event_type, :notice => 'Event type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /event_types/1
  # DELETE /event_types/1.xml
  def destroy
    @event_type = EventType.find(params[:id])
    @event_type.destroy

    respond_to do |format|
      format.html { redirect_to(event_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/event_types_helper.rb
module EventTypesHelper
end

app/views/event_types/_form.html.erb
<%= form_for(@event_type) do |f| %>
  <% if @event_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_type.errors.count, "error") %> prohibited this event_type from being saved:</h2>

      <ul>
      <% @event_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %><br />
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_types/edit.html.erb
<h1>Editing event_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_type %> |
<%= link_to 'Back', event_types_path %>

app/views/event_types/index.html.erb
<h1>Listing event_types</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @event_types.each do |event_type| %>
  <tr>
    <td><%= event_type.event %></td>
    <td><%= event_type.description %></td>
    <td><%= link_to 'Show', event_type %></td>
    <td><%= link_to 'Edit', edit_event_type_path(event_type) %></td>
    <td><%= link_to 'Destroy', event_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event type', new_event_type_path %>

app/views/event_types/new.html.erb
<h1>New event_type</h1>

<%= render 'form' %>

<%= link_to 'Back', event_types_path %>

app/views/event_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @event_type.event %>
</p>

<p>
  <b>Description:</b>
  <%= @event_type.description %>
</p>


<%= link_to 'Edit', edit_event_type_path(@event_type) %> |
<%= link_to 'Back', event_types_path %>